server:
  port: 9000

spring:
  application:
    name: silver-gateway
  config:
    import: optional:nacos:
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      discovery:
        enabled: ${NACOS_ENABLED:true}
      config:
        enabled: ${NACOS_ENABLED:true}
      import-check:
        enabled: false
    gateway:
      routes:
        - id: user-service
          uri: lb://silver-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: content-service
          uri: lb://silver-content
          predicates:
            - Path=/api/content/**
          filters:
            - StripPrefix=1
        - id: course-service
          uri: lb://silver-course
          predicates:
            - Path=/api/course/**
          filters:
            - StripPrefix=1

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 2592000
  is-concurrent: true
  is-share: true
  jwt-secret-key: ${SA_TOKEN_JWT_SECRET:silver-wisdom-jwt-secret}

management:
  endpoints:
    web:
      exposure:
        include: health,info
